### ISSUE TITLE
Implement ERC1155 in Sable Trove

### ISSUE THREAD

**Issue by RyRy79261** [Mic-fox/booster-stream#4]
## Description 

`SableTrove.sol` needs to implement ERC1155 token standard from [Open Zeppelin](https://docs.openzeppelin.com/contracts/4.x/erc1155)

The `ERC1155PresetMinterPauser` preset should used, the tests have been added and once they're passing then the ticket is complete 

The development framework is called Hardhat, and you can read up on how the tests are managed here: 
https://hardhat.org/tutorial/testing-contracts.html

## Steps

Create a branch called `feat/sable-trove-erc1155-4` (The `4` at the end refers to this issue's ID number)

Then to run the tests, run `yarn test:chain` 

You will find the contracts in `packages/chain/contracts` 

To see what contracts OpenZepplin has or to see what the contracts do, open `./node_modules/@openzeppelin/contracts/token/`

## Tasks

- [x] Convert SableTrove to ERC1155Preset 
- [ ] Complete the `ERC1155PresetMinterPauser` test collection
- [ ] Complete the `View functions` test collection
- [ ] Complete the `Events` test collection (Optional)

**Comment by RyRy79261** [comment]
# Requires https://github.com/Mic-fox/booster-stream/pull/5 to be merged
